export const loadoutDefaultValues = {
    title: '',
    weapon: '',
    gameMode: '',
    description: '',
    imageUrl: '',
    firstAttachment: '',
    secondAttachment: '',
    thirdAttachment: '',
    fourthAttachment: '',
    fifthAttachment: '',
    categoryId: '',
}



export const weapons = [
    { label: "AK-47", value: "AK-47" },
    { label: "Man-O-War", value: "Man-O-War" },
    { label: "M13", value: "M13" },
    { label: "Kilo 141", value: "Kilo 141" },
    { label: "Type 25", value: "Type 25" },
    { label: "ASM10", value: "ASM10" },
    { label: "ICR-1", value: "ICR-1" },
    { label: "DR-H", value: "DR-H" },
    { label: "Cordite", value: "Cordite" },
    { label: "LK24", value: "LK24" },
    { label: "HVK-30", value: "HVK-30" },
    { label: "KN-44", value: "KN-44" },
    { label: "M4", value: "M4" },
    { label: "QQ9", value: "QQ9" },
    { label: "AS VAL", value: "AS VAL" },
    { label: "AK117", value: "AK117" },
    { label: "RUS-79", value: "RUS-79" },
    { label: "Pharo", value: "Pharo" },
    { label: "GKS", value: "GKS" },
    { label: "MP5", value: "MP5" },
    { label: "CBR4", value: "CBR4" },
    { label: "Fennec", value: "Fennec" },
    { label: "MAC-10", value: "MAC-10" },
    { label: "P90", value: "P90" },
    { label: "Bizon", value: "Bizon" },
    { label: "HG-40", value: "HG-40" },
    { label: "QXR", value: "QXR" },
    { label: "MX9", value: "MX9" },
    { label: "Switchblade X9", value: "Switchblade X9" },
    { label: "PPSh-41", value: "PPSh-41" },
    { label: "DL Q33", value: "DL Q33" },
    { label: "Locus", value: "Locus" },
    { label: "ZRG 20mm", value: "ZRG 20mm" },
    { label: "Arctic .50", value: "Arctic .50" },
    { label: "M21 EBR", value: "M21 EBR" },
    { label: "SVD", value: "SVD" },
    { label: "XPR-50", value: "XPR-50" },
    { label: "K98", value: "K98" },
    { label: "SP-R 208", value: "SP-R 208" },
    { label: "MK2 Carbine", value: "MK2 Carbine" },
    { label: "M4LMG", value: "M4LMG" },
    { label: "PKP Pecheneg", value: "PKP Pecheneg" },
    { label: "Holger-26", value: "Holger-26" },
    { label: "RPD", value: "RPD" },
    { label: "UL736", value: "UL736" },
    { label: "SA87", value: "SA87" },
    { label: "R90", value: "R90" },
    { label: "Hades", value: "Hades" },
    { label: "Dingo LMG", value: "Dingo LMG" },
    { label: "Chopper", value: "Chopper" },
    { label: "Model 680", value: "Model 680" },
    { label: "KRM-262", value: "KRM-262" },
    { label: "HS2126", value: "HS2126" },
    { label: "Striker", value: "Striker" },
    { label: "JAK-12", value: "JAK-12" },
    { label: "Echo", value: "Echo" },
    { label: "BY15", value: "BY15" },
    { label: "MW11", value: "MW11" },
    { label: "J358", value: "J358" },
    { label: "Renati Stealth", value: "Renati Stealth" },
    { label: "L-CAR 9", value: "L-CAR 9" },
    { label: "Marshal", value: "Marshal" },
    { label: "Deagle", value: "Deagle" },
    { label: "Secondary Shotguns", value: "Secondary Shotguns" },
    { label: "Shorty", value: "Shorty" },
] as const;


export const firstAttachments = [
    { label: "Red Dot Sight", value: "Red Dot Sight" },
    { label: "Holographic Sight", value: "Holographic Sight" },
    { label: "Tactical Scope", value: "Tactical Scope" },
    { label: "3X Scope", value: "3X Scope" },
    { label: "4X Scope", value: "4X Scope" },
    { label: "Sniper Scope", value: "Sniper Scope" },
    { label: "Suppressor", value: "Suppressor" },
    { label: "Flash Hider", value: "Flash Hider" },
    { label: "Compensator", value: "Compensator" },
    { label: "Muzzle Brake", value: "Muzzle Brake" },
    { label: "Extended Barrel", value: "Extended Barrel" },
    { label: "Short Barrel", value: "Short Barrel" },
    { label: "Foregrip", value: "Foregrip" },
    { label: "Vertical Foregrip", value: "Vertical Foregrip" },
    { label: "Angled Grip", value: "Angled Grip" },
    { label: "Operator Foregrip", value: "Operator Foregrip" },
    { label: "Extended Mag", value: "Extended Mag" },
    { label: "Fast Mag", value: "Fast Mag" },
    { label: "Drum Mag", value: "Drum Mag" },
    { label: "Tactical Stock", value: "Tactical Stock" },
    { label: "Light Stock", value: "Light Stock" },
    { label: "Collapsible Stock", value: "Collapsible Stock" },
    { label: "Stippled Grip Tape", value: "Stippled Grip Tape" },
    { label: "Rubberized Grip Tape", value: "Rubberized Grip Tape" },
    { label: "Tac Laser", value: "Tac Laser" },
    { label: "5mW Laser", value: "5mW Laser" },
] as const

export const secondAttachments = [
    { label: "Red Dot Sight", value: "Red Dot Sight" },
    { label: "Holographic Sight", value: "Holographic Sight" },
    { label: "Tactical Scope", value: "Tactical Scope" },
    { label: "3X Scope", value: "3X Scope" },
    { label: "4X Scope", value: "4X Scope" },
    { label: "Sniper Scope", value: "Sniper Scope" },
    { label: "Suppressor", value: "Suppressor" },
    { label: "Flash Hider", value: "Flash Hider" },
    { label: "Compensator", value: "Compensator" },
    { label: "Muzzle Brake", value: "Muzzle Brake" },
    { label: "Extended Barrel", value: "Extended Barrel" },
    { label: "Short Barrel", value: "Short Barrel" },
    { label: "Foregrip", value: "Foregrip" },
    { label: "Vertical Foregrip", value: "Vertical Foregrip" },
    { label: "Angled Grip", value: "Angled Grip" },
    { label: "Operator Foregrip", value: "Operator Foregrip" },
    { label: "Extended Mag", value: "Extended Mag" },
    { label: "Fast Mag", value: "Fast Mag" },
    { label: "Drum Mag", value: "Drum Mag" },
    { label: "Tactical Stock", value: "Tactical Stock" },
    { label: "Light Stock", value: "Light Stock" },
    { label: "Collapsible Stock", value: "Collapsible Stock" },
    { label: "Stippled Grip Tape", value: "Stippled Grip Tape" },
    { label: "Rubberized Grip Tape", value: "Rubberized Grip Tape" },
    { label: "Tac Laser", value: "Tac Laser" },
    { label: "5mW Laser", value: "5mW Laser" },
] as const

export const thirdAttachments = [
    { label: "Red Dot Sight", value: "Red Dot Sight" },
    { label: "Holographic Sight", value: "Holographic Sight" },
    { label: "Tactical Scope", value: "Tactical Scope" },
    { label: "3X Scope", value: "3X Scope" },
    { label: "4X Scope", value: "4X Scope" },
    { label: "Sniper Scope", value: "Sniper Scope" },
    { label: "Suppressor", value: "Suppressor" },
    { label: "Flash Hider", value: "Flash Hider" },
    { label: "Compensator", value: "Compensator" },
    { label: "Muzzle Brake", value: "Muzzle Brake" },
    { label: "Extended Barrel", value: "Extended Barrel" },
    { label: "Short Barrel", value: "Short Barrel" },
    { label: "Foregrip", value: "Foregrip" },
    { label: "Vertical Foregrip", value: "Vertical Foregrip" },
    { label: "Angled Grip", value: "Angled Grip" },
    { label: "Operator Foregrip", value: "Operator Foregrip" },
    { label: "Extended Mag", value: "Extended Mag" },
    { label: "Fast Mag", value: "Fast Mag" },
    { label: "Drum Mag", value: "Drum Mag" },
    { label: "Tactical Stock", value: "Tactical Stock" },
    { label: "Light Stock", value: "Light Stock" },
    { label: "Collapsible Stock", value: "Collapsible Stock" },
    { label: "Stippled Grip Tape", value: "Stippled Grip Tape" },
    { label: "Rubberized Grip Tape", value: "Rubberized Grip Tape" },
    { label: "Tac Laser", value: "Tac Laser" },
    { label: "5mW Laser", value: "5mW Laser" },
] as const

export const fourthAttachments = [
    { label: "Red Dot Sight", value: "Red Dot Sight" },
    { label: "Holographic Sight", value: "Holographic Sight" },
    { label: "Tactical Scope", value: "Tactical Scope" },
    { label: "3X Scope", value: "3X Scope" },
    { label: "4X Scope", value: "4X Scope" },
    { label: "Sniper Scope", value: "Sniper Scope" },
    { label: "Suppressor", value: "Suppressor" },
    { label: "Flash Hider", value: "Flash Hider" },
    { label: "Compensator", value: "Compensator" },
    { label: "Muzzle Brake", value: "Muzzle Brake" },
    { label: "Extended Barrel", value: "Extended Barrel" },
    { label: "Short Barrel", value: "Short Barrel" },
    { label: "Foregrip", value: "Foregrip" },
    { label: "Vertical Foregrip", value: "Vertical Foregrip" },
    { label: "Angled Grip", value: "Angled Grip" },
    { label: "Operator Foregrip", value: "Operator Foregrip" },
    { label: "Extended Mag", value: "Extended Mag" },
    { label: "Fast Mag", value: "Fast Mag" },
    { label: "Drum Mag", value: "Drum Mag" },
    { label: "Tactical Stock", value: "Tactical Stock" },
    { label: "Light Stock", value: "Light Stock" },
    { label: "Collapsible Stock", value: "Collapsible Stock" },
    { label: "Stippled Grip Tape", value: "Stippled Grip Tape" },
    { label: "Rubberized Grip Tape", value: "Rubberized Grip Tape" },
    { label: "Tac Laser", value: "Tac Laser" },
    { label: "5mW Laser", value: "5mW Laser" },
] as const

export const fifthAttachments = [
    { label: "Red Dot Sight", value: "Red Dot Sight" },
    { label: "Holographic Sight", value: "Holographic Sight" },
    { label: "Tactical Scope", value: "Tactical Scope" },
    { label: "3X Scope", value: "3X Scope" },
    { label: "4X Scope", value: "4X Scope" },
    { label: "Sniper Scope", value: "Sniper Scope" },
    { label: "Suppressor", value: "Suppressor" },
    { label: "Flash Hider", value: "Flash Hider" },
    { label: "Compensator", value: "Compensator" },
    { label: "Muzzle Brake", value: "Muzzle Brake" },
    { label: "Extended Barrel", value: "Extended Barrel" },
    { label: "Short Barrel", value: "Short Barrel" },
    { label: "Foregrip", value: "Foregrip" },
    { label: "Vertical Foregrip", value: "Vertical Foregrip" },
    { label: "Angled Grip", value: "Angled Grip" },
    { label: "Operator Foregrip", value: "Operator Foregrip" },
    { label: "Extended Mag", value: "Extended Mag" },
    { label: "Fast Mag", value: "Fast Mag" },
    { label: "Drum Mag", value: "Drum Mag" },
    { label: "Tactical Stock", value: "Tactical Stock" },
    { label: "Light Stock", value: "Light Stock" },
    { label: "Collapsible Stock", value: "Collapsible Stock" },
    { label: "Stippled Grip Tape", value: "Stippled Grip Tape" },
    { label: "Rubberized Grip Tape", value: "Rubberized Grip Tape" },
    { label: "Tac Laser", value: "Tac Laser" },
    { label: "5mW Laser", value: "5mW Laser" },
] as const